server.port: 7001
server.error.include-message: always

#MNote, p175
#without Docker using the default Spring profile, reaches database on localhost:27017
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.framework: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
#MNote, p101, 02
#Create a new Spring profile named docker to be used when we run our microservices as containers in Docker
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb