server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    com.framework: DEBUG

---
#MNote, p101, 02
#Create a new Spring profile named docker to be used when we run our microservices as containers in Docker
spring.config.activate.on-profile: docker

server.port: 8080