server.port: 7003
server.error.include-message: always

#MNote, p176
# Set this property to "none" in a production environment
# his prevents Spring Data JPA from manipulating the structure of the SQL tables
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

#MNote, p177
# By default, HikariCP is used by Spring Data JPA as the JDBC connection pool.
# To minimize startup problems on computers with limited hardware resources,
# the initializationFailTimeout parameter is set to 60 seconds.
spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.framework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
#MNote, p101, 04
#Create a new Spring profile named docker to be used when we run our microservices as containers in Docker
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db